# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('\u041f\u0410\u0420\u041d\u042b\u0419', '\u041f\u0410\u0420\u041d\u042b\u0419'), ('\u041a\u041e\u041c\u0410\u041d\u0414\u041d\u042b\u0419', '\u041a\u041e\u041c\u0410\u041d\u0414\u041d\u042b\u0419')], default='\u041a\u041e\u041c\u0410\u041d\u0414\u041d\u042b\u0419', max_length=255)),
            ],
            options={
                'verbose_name': '\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='ActivityPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('min_people', models.IntegerField()),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Activity')),
            ],
            options={
                'verbose_name': '\u0421\u043e\u0431\u044b\u0442\u0438\u0435',
                'verbose_name_plural': '\u0421\u043e\u0431\u044b\u0442\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='EventUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('website', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0441\u0442\u043e',
                'verbose_name_plural': '\u041c\u0435\u0441\u0442\u0430',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(through='event.EventUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityplaces',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Place'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_places',
            field=models.ManyToManyField(through='event.ActivityPlaces', to='event.Place'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_users',
            field=models.ManyToManyField(through='event.ActivityUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventusers',
            unique_together=set([('event', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='activityusers',
            unique_together=set([('user', 'activity')]),
        ),
    ]
