# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20160210_0820'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place',
            table='\u041c\u0435\u0441\u0442\u043e',
        ),
    ]
