# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20160216_1409'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place',
            table=None,
        ),
    ]
