# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20160216_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c', 'verbose_name_plural': '\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u0438'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '\u0421\u043e\u0431\u044b\u0442\u0438\u0435', 'verbose_name_plural': '\u0421\u043e\u0431\u044b\u0442\u0438\u044f'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': '\u041c\u0435\u0441\u0442\u043e', 'verbose_name_plural': '\u041c\u0435\u0441\u0442\u0430'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '\u041a\u043e\u043c\u0430\u043d\u0434\u0430', 'verbose_name_plural': '\u041a\u043e\u043c\u0430\u043d\u0434\u044b'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
