# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20160216_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schedule_to_play',
            field=models.CharField(blank=True, choices=[('\u0412\u0421\u0415\u0413\u0414\u0410', '\u0412\u0421\u0415\u0413\u0414\u0410'), ('\u0411\u0423\u0414\u041d\u0418', '\u0411\u0423\u0414\u041d\u0418'), ('\u0412\u042b\u0425\u041e\u0414\u041d\u042b\u0415', '\u0412\u042b\u0425\u041e\u0414\u041d\u042b\u0415')], default='\u0412\u0421\u0415\u0413\u0414\u0410', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('\u041c\u0423\u0416\u0421\u041a\u041e\u0419', '\u041c\u0423\u0416\u0421\u041a\u041e\u0419'), ('\u0416\u0415\u041d\u0421\u041a\u0418\u0419', '\u0416\u0415\u041d\u0421\u041a\u0418\u0419')], max_length=100, null=True),
        ),
    ]
